# Generated by Django 5.1.7 on 2025-03-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0003_livros_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ISBN',
            field=models.IntegerField(max_length=13),
        ),
    ]
